The scheduler does not know why the exception was called as as such does not know what the next state will be.